---
version: 0.2
phases:
  install:
    commands:
      - "apt-get -qq update"
      - "apt-get -qq install libyaml-dev"
      - "make setup"
  build:
    commands:
      - "make check"
artifacts: {}
cache:
  paths:
    - /root/.cache/pip/**/*
